[ssh]
# required IPv4 address can be define here.
address = "103.13.206.130"
# optional, by default is "root"
username = "administrator"
# You can choose one using "password" or "private_key"
password = "Code4Live@12$"
# optional if do you want to connect via private_key
# private_key = "/Users/adiatma/.ssh/id_ed25519"
# optional by default port 22, but you can customize by your self.
# port = 22

[server]
# scp is optional, if do you want to copy file from local to the server, can be define here.
# scp = [ "docker-compose.yaml" ]
# ssh commands if do you want to exec script or anything on the server.
commands = [
  "dir",
  "powershell -command Install-Module -Name DockerMsftProvider -Repository PSGallery -Force",
  "powershell -command Install-Package -Name docker -ProviderName DockerMsftProvider",
]
